# Generated by Django 3.1.2 on 2023-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.DateField(max_length=10)),
                ('lte_exists', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
